apiVersion: v1
kind: Pod
metadata:
  name: niginx-resources
spec:
  containers:
    - name: nginx-resources
      image: nginx:latest
      resources: # Minimum resources guaranteed to the container
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits: # Maximum resources the container can consume
          memory: "256Mi"
          cpu: "200m"