apiVersion: v1
kind: Pod
metadata:
  name: nginx-env
spec:
  containers:
    - name: nginx-env
      image: nginx:latest
      env:
        - name: Environment
          value: dev
        - name: project
          value: roboshop
        - name: purpose
          value: POC
