apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    environment: dev
spec: 
  # Service uses following labels to select the appropriate pods
  selector:
    name: roboshop
    tier: frontend
    component: frontend
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: roboshop
    tier: frontend
    component: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx

