apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    name: nginx-lb
    environment: dev
spec:
  type: LoadBalancer
  # Service uses following labels to select the appropriate pods
  selector:
    name: roboshop
    tier: frontend
    component: frontend
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port
      nodePort: 30080 #node port for LoadBalancer