apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    component: frontend
    tier: frontend
    purpose: Deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      project: roboshop
      component: frontend
      tier: frontend
      purpose: Deployment
  template:
    metadata:
      labels:
        project: roboshop
        component: frontend
        tier: frontend
        purpose: Deployment
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
